# Copyright 2018 Google LLC
# Modifications copyright 2026 RefactorLabs
#
# Licensed under the Apache License, Version 2.0 (the "License").
"""JSON-native profile schema.

Replaces the deleted `profile_pb2.py`. The original was a protobuf
descriptor for `perftools.profiles.Profile` (the pprof binary format)
generated by `protoc`. With protobuf gone, we still need a SCHEMA —
otherwise every emit site duplicates the shape of an event, and any
change has to be made in many places.

This module defines that schema as plain Python dataclasses. The
JSON-native form drops one feature from pprof — the deduplicated
`string_table[]` + integer indices — because JSON has no real win
from that indirection and tools like jq, ripgrep, and DuckDB read
inline strings directly. Everything else (Profile, ValueType, Sample,
Frame, plus the Builder API) mirrors pprof's structure 1:1.

Two output shapes are supported on top of this schema:

  - **per-trace**: each Sample is serialized as its own JSON object.
    Cheap to tail, easy to grep, one trace per line.
  - **bundle**:    a whole Profile (one window's worth of samples) is
    serialized as one JSON object on one line.

The agent picks between them via `emit_mode='per_trace' | 'bundle'`.
The schema below is the source of truth for both shapes.
"""

import time
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional


# ----------------------------------------------------------------- schema

@dataclass
class ValueType:
  """Counterpart of pprof's `ValueType` message. Describes what a column
  of `Sample.value` means — e.g. `('wall', 'nanoseconds')`."""
  type: str
  unit: str


@dataclass
class Frame:
  """One stack frame. JSON-native counterpart of pprof's
  `Location` + `Line` + `Function` triple. We flatten the three into
  one because, without a string_table, the indirection costs more JSON
  than it saves."""
  name: str
  file: str
  line: int


@dataclass
class Sample:
  """Counterpart of pprof's `Sample` message. `count` is the number of
  ticks that hit this stack; `value_ns` is `count * period_ns` (i.e.
  total wall- or CPU-time attributed to this stack). `frames` is the
  call stack, leaf-first."""
  count: int
  value_ns: int
  frames: List[Frame] = field(default_factory=list)
  labels: Dict[str, str] = field(default_factory=dict)


@dataclass
class Profile:
  """Counterpart of pprof's top-level `Profile` message.

  `profile_type` is `"wall"` or `"cpu"` (pprof's `period_type.type`).
  `period_ns` and `duration_ns` carry the same meaning as in pprof.
  `time_ns` is the window-end timestamp (ns since epoch).
  `cpu` is the 1-minute system load average at window close.
  `memory_bytes` is the process RSS at window close.
  """
  profile_type: str
  period_ns: int
  duration_ns: int
  time_ns: int
  sample_type: List[ValueType] = field(default_factory=list)
  samples: List[Sample] = field(default_factory=list)
  service: str = ''
  pod: str = ''
  service_version: str = ''
  cpu: float = 0.0
  memory_bytes: int = 0
  default_sample_type: Optional[str] = None
  comment: List[str] = field(default_factory=list)

  def to_dict(self) -> Dict[str, Any]:
    """Plain `dict` representation; the writer does the json.dumps."""
    return asdict(self)


# ----------------------------------------------------------------- builder

class Builder:
  """Builds a `Profile` from a `{trace: count}` dict.

  Two-step API: `populate_profile()` to fill it in, `to_dict()` to get
  the plain dict the writer serializes. The intermediate `to_profile()`
  exists so callers can grab the typed dataclass before flattening.
  """

  def __init__(self):
    self._profile: Optional[Profile] = None

  def populate_profile(self,
                       traces,
                       profile_type,
                       period_unit,
                       period,
                       duration_ns,
                       time_ns=None,
                       service='',
                       pod='',
                       service_version='',
                       cpu=0.0,
                       memory_bytes=0,
                       is_system_predicate=None):
    """Build the underlying `Profile` from raw traces.

    Args:
      traces: A `dict[tuple[(name, file, line), ...], int]` — the
        exact shape that `WallProfiler.profile()` and
        `CPUProfiler.profile()` return.
      profile_type: `'wall'` or `'cpu'`.
      period_unit: e.g. `'nanoseconds'`.
      period: The sampling period in `period_unit` units.
      duration_ns: Profile window duration in nanoseconds.
      time_ns: Window-end timestamp (ns). Defaults to `time.time_ns()`.
      service / pod / service_version: Optional labels stamped on
        the Profile (and therefore on every emitted line).
      is_system_predicate: Phase F1a. Optional ``(file: str) -> bool``
        callback. When supplied, every emitted frame gains
        ``language='python'``, ``is_native=False``, and ``is_system``
        derived from the predicate — matching the static profiler's
        ``Frame`` schema for join-by-key consumers. When ``None``
        (the back-compat default), frames are emitted in the legacy
        ``{name, file, line}`` shape via the ``Frame`` dataclass.
    """
    samples: List[Sample] = []
    for trace, count in traces.items():
      # Phase F1a + F1b: when enrichment is requested OR the input
      # has F1b's wider 5-tuple shape, emit plain dicts that carry
      # the optional fields. The Frame dataclass intentionally
      # doesn't model the new fields — adding them as
      # ``Optional[...] = None`` would serialize them as ``null`` in
      # every emitted bundle (asdict has no way to drop None), which
      # would break the "additive schema" promise. Bypassing the
      # dataclass for the enriched path keeps absent fields absent.
      first = trace[0] if trace else ()
      has_f1b_shape = len(first) >= 5
      if is_system_predicate is None and not has_f1b_shape:
        frames = [Frame(name=f[0], file=f[1], line=f[2]) for f in trace]
      else:
        frames = []
        for f in trace:
          d = {'name': f[0], 'file': f[1], 'line': f[2]}
          if len(f) >= 5:
            if f[3]:
              d['qualified_name'] = f[3]
            if f[4]:
              d['module'] = f[4]
          if is_system_predicate is not None:
            d['language'] = 'python'
            d['is_native'] = False
            d['is_system'] = bool(is_system_predicate(f[1]))
          frames.append(d)
      icount = int(count)
      samples.append(Sample(
          count=icount,
          value_ns=int(period) * icount,
          frames=frames,
      ))

    self._profile = Profile(
        profile_type=profile_type,
        period_ns=int(period),
        duration_ns=int(duration_ns),
        time_ns=int(time_ns) if time_ns is not None else time.time_ns(),
        sample_type=[
            ValueType(type='sample', unit='count'),
            ValueType(type=profile_type, unit=period_unit),
        ],
        samples=samples,
        service=service,
        pod=pod,
        service_version=service_version,
        cpu=float(cpu),
        memory_bytes=int(memory_bytes),
    )

  def to_profile(self) -> Profile:
    """Return the underlying `Profile` dataclass."""
    if self._profile is None:
      raise RuntimeError(
          'Builder.to_profile() called before populate_profile()')
    return self._profile

  def to_dict(self) -> Dict[str, Any]:
    """Plain dict — convenient for callers that want to add labels
    before serializing."""
    return self.to_profile().to_dict()


# ----------------------------------------------------------------- helpers

def bundle_event_type(profile_type: str) -> str:
  """Resolve `'wall'` / `'cpu'` to the bundle event-type string."""
  return profile_type + '_profile'


def per_trace_event_type(profile_type: str) -> str:
  """Resolve `'wall'` / `'cpu'` to the per-trace event-type string."""
  return profile_type + '_trace'
