import { useEffect, useRef, useState } from 'react';
import { APP_NAME } from '../config';
import { patchSettings, type Settings } from '../state/settings';
import { usePrContext } from '../state/prContext';
import { FileModal } from './FileModal';
import { FileIcon } from './FileIcon';
import { AudioSummary } from './AudioSummary';
import { buildReasoning, reasoningTitle, type ReasoningStep } from './reasoning';
import { getChat, saveChat, clearChat, type ChatMessage } from '../state/chatHistory';
import type { ArtifactRef, PrContext } from '../core/types';
import { type Turn } from '../core/chatContext';
import { DEFAULT_PERSONA } from '../core/brainConstants';
import { getSharedBrain } from '../core/brainEngine';
import { isBrainSupported } from '../core/brainRuntime';
import { downloadBrain, isBrainAvailable, type AcquireProgress } from '../core/brainStore';
import { VoiceController, type VoiceState } from '../core/voiceController';
import { VoiceOrb } from './VoiceOrb';
import { useActivePr } from '../state/activePr';
import { runAgentTurn } from '../core/agentLoop';
import { EMPTY_PR_STATE, type PrToolState } from '../core/chatTools';
import { LENSES } from '../agents/lenses';
import { latestScanForPr, prUrl } from '../core/runLiveScan';

const STEP_INTERVAL_MS = 450;

/** Brain lifecycle as the chat sees it. */
type BrainState = 'checking' | 'unsupported' | 'needs-download' | 'downloading' | 'ready' | 'error';

// The chat surface. Conversations are persisted per PR url (chat history), so
// revisiting a PR restores its conversation instantly. The reply is generated by
// the in-browser LLM brain (Qwen via WebLLM) — tokens stream into a live bubble.
export function Chat({
  settings,
  onOpenSettings,
  onOpenContext,
  onOpenPipeline,
}: {
  settings: Settings;
  onOpenSettings: () => void;
  onOpenContext: () => void;
  onOpenPipeline: () => void;
}) {
  // The conversation is bound to a PR url so persistence is always atomic.
  const [chat, setChat] = useState<{ url: string | null; messages: ChatMessage[] }>({
    url: null,
    messages: [],
  });
  const messages = chat.messages;
  const [draft, setDraft] = useState('');
  const [modalFile, setModalFile] = useState<ArtifactRef | null>(null);
  const [brainState, setBrainState] = useState<BrainState>('checking');
  const [dlProgress, setDlProgress] = useState<AcquireProgress | null>(null);
  const [busy, setBusy] = useState(false);
  const [voiceStatus, setVoiceStatus] = useState<string | null>(null);
  const [mode, setMode] = useState<'text' | 'voice'>('text');
  const [voiceState, setVoiceState] = useState<VoiceState>('idle');
  const controllerRef = useRef<VoiceController | null>(null);
  const voiceReplyId = useRef<number | null>(null);
  const voiceToolMsgId = useRef<number | null>(null); // current tool-step card id in voice mode
  const voiceLevel = useRef(0); // 0..1 energy for the orb (written per audio frame, never setState)
  const nextId = useRef(1);
  const scrollRef = useRef<HTMLDivElement>(null);
  const chatRef = useRef(chat);
  chatRef.current = chat;
  const targetUrl = useRef<string | null>(null);
  const streamIv = useRef<number | null>(null);
  const genAbort = useRef<AbortController | null>(null);
  const { ctx, refresh } = usePrContext();
  const activePr = useActivePr();

  // PR/scan tool state — surfaced in the chip AND injected into the agent prompt.
  // `scanRan`/`changedCount` seed from history; `scanRunning` flips during a tool.
  const [toolState, setToolState] = useState<PrToolState>(EMPTY_PR_STATE);
  const toolStateRef = useRef(toolState);
  toolStateRef.current = toolState;

  // Recompute tool state when the active PR changes: read the latest scan from
  // history (cache, no network) so "scan ran" + file count are known up front.
  useEffect(() => {
    let alive = true;
    if (!activePr) {
      setToolState(EMPTY_PR_STATE);
      return;
    }
    const base: PrToolState = {
      pr: activePr,
      url: prUrl(activePr),
      title: ctx?.pr.title ?? null,
      scanRan: false,
      scanRunning: false,
      changedCount: null,
      architectureKnown: false,
    };
    setToolState(base);
    void latestScanForPr(activePr).then((rec) => {
      if (!alive || !rec) return;
      setToolState((s) => ({ ...s, scanRan: true, changedCount: rec.changedFiles ?? null }));
    });
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activePr?.owner, activePr?.repo, activePr?.number, ctx?.pr.title]);

  const scrollToBottom = () => {
    requestAnimationFrame(() => {
      scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    });
  };

  const stopStream = () => {
    if (streamIv.current != null) {
      window.clearInterval(streamIv.current);
      streamIv.current = null;
    }
  };

  // Probe the brain on mount: is WebGPU here, and has the model been downloaded?
  useEffect(() => {
    let alive = true;
    (async () => {
      if (!(await isBrainSupported())) {
        if (alive) setBrainState('unsupported');
        return;
      }
      const ready = await isBrainAvailable();
      if (alive) setBrainState(ready ? 'ready' : 'needs-download');
    })();
    return () => {
      alive = false;
    };
  }, []);

  // Stream the step-by-step reasoning turn for a freshly-detected PR.
  function startReasoning(c: PrContext) {
    const allSteps = buildReasoning(c);
    const id = nextId.current++;
    setChat((prev) =>
      prev.messages.some((x) => x.steps && x.prUrl === c.pr.url)
        ? prev
        : {
            ...prev,
            messages: [
              ...prev.messages,
              { id, role: 'assistant', title: reasoningTitle(c), steps: [], thinking: true, prUrl: c.pr.url },
            ],
          },
    );
    let shown = 0;
    stopStream();
    streamIv.current = window.setInterval(() => {
      shown += 1;
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((x) =>
          x.id === id ? { ...x, steps: allSteps.slice(0, shown), thinking: shown < allSteps.length } : x,
        ),
      }));
      scrollToBottom();
      if (shown >= allSteps.length) stopStream();
    }, STEP_INTERVAL_MS);
  }

  // Switch conversation when the active PR changes: persist the outgoing one,
  // restore the incoming one from storage (instant), or stream it fresh.
  useEffect(() => {
    const url = ctx?.pr.url ?? null;
    if (url === chatRef.current.url) return;
    targetUrl.current = url;

    const prev = chatRef.current;
    if (prev.url && prev.messages.length) void saveChat(prev.url, prev.messages);
    stopStream();

    if (!url || !ctx) {
      setChat({ url, messages: [] });
      syncVoiceTo([]); // a live voice session must drop the old PR's context
      return;
    }
    const pr = ctx;
    void getChat(url).then((saved) => {
      if (targetUrl.current !== url) return; // navigated again — drop stale load
      if (saved.length) {
        nextId.current = Math.max(0, ...saved.map((m) => m.id)) + 1;
        setChat({ url, messages: saved }); // instant restore — no re-stream
        syncVoiceTo(historyTurns(saved, -1));
      } else {
        setChat({ url, messages: [] });
        syncVoiceTo([]);
        startReasoning(pr);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx?.pr.url]);

  // Persist the conversation (debounced) under its PR url.
  useEffect(() => {
    if (!chat.url) return;
    const t = window.setTimeout(() => void saveChat(chat.url!, chat.messages), 500);
    return () => window.clearTimeout(t);
  }, [chat]);

  // Stop any running stream / generation when the panel unmounts.
  useEffect(
    () => () => {
      stopStream();
      genAbort.current?.abort();
      void controllerRef.current?.stop();
    },
    [],
  );

  // Build the persona, grounding it in the active PR when one is loaded.
  function persona(): string {
    const base = settings.persona?.trim() || DEFAULT_PERSONA;
    if (!ctx) return base;
    return `${base}\n\nContext: the user is viewing pull request ${ctx.pr.repo}#${ctx.pr.number} — "${ctx.pr.title ?? ''}". Ground your answers in this PR when relevant.`;
  }

  // Re-ground a LIVE voice session on a new conversation (PR switch / new chat).
  // The controller captured the old PR's persona + context at start and lives
  // across navigation, so without this it keeps talking about the old PR. No-op
  // in text mode (no controller).
  function syncVoiceTo(history: Turn[]) {
    const vc = controllerRef.current;
    if (!vc) return;
    voiceReplyId.current = null;
    voiceToolMsgId.current = null;
    vc.resetConversation(persona(), history);
  }

  // Project the visible transcript into chat turns for the brain (skip reasoning
  // steps — they have no plain text — and the live placeholder being filled).
  function historyTurns(msgs: ChatMessage[], skipId: number): Turn[] {
    const turns: Turn[] = [];
    for (const m of msgs) {
      if (m.id === skipId || m.steps || !m.text) continue;
      turns.push({ role: m.role === 'assistant' ? 'agent' : 'user', text: m.text });
    }
    return turns;
  }

  // One conversational turn: append the user message + a live assistant bubble,
  // then stream tokens from the brain into it. Shared by text send + voice mode.
  async function runTurn(userText: string) {
    const text = userText.trim();
    if (!text || busy) return;
    if (brainState !== 'ready') {
      // No brain — surface the reason instead of pretending to answer.
      setChat((prev) => ({
        ...prev,
        messages: [
          ...prev.messages,
          { id: nextId.current++, role: 'user', text },
          {
            id: nextId.current++,
            role: 'assistant',
            text:
              brainState === 'unsupported'
                ? 'This browser has no WebGPU, so the on-device AI can’t run here.'
                : 'Download the AI model first (Settings → Download AI model).',
          },
        ],
      }));
      scrollToBottom();
      return;
    }

    const userMsg: ChatMessage = { id: nextId.current++, role: 'user', text };
    const replyId = nextId.current++;
    const replyMsg: ChatMessage = { id: replyId, role: 'assistant', text: '', thinking: true };
    setChat((prev) => ({ ...prev, messages: [...prev.messages, userMsg, replyMsg] }));
    scrollToBottom();

    const prior = historyTurns(chatRef.current.messages, replyId);

    const abort = new AbortController();
    genAbort.current = abort;
    setBusy(true);
    // Track the tool-step card id for the in-flight tool (one at a time).
    let toolMsgId: number | null = null;
    try {
      const brain = await getSharedBrain();
      await runAgentTurn({
        brain,
        persona: persona(),
        history: prior,
        userText: text,
        getState: () => toolStateRef.current,
        signal: abort.signal,
        events: {
          onToken: (delta) => {
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) =>
                m.id === replyId ? { ...m, text: (m.text ?? '') + delta, thinking: false } : m,
              ),
            }));
            scrollToBottom();
          },
          onToolStart: (tool) => {
            const id = nextId.current++;
            toolMsgId = id;
            setToolState((s) => ({ ...s, scanRunning: tool === 'run_live_pr_scan' ? true : s.scanRunning }));
            // Insert the tool-step card BEFORE the (still-empty) reply bubble.
            setChat((prev) => {
              const reply = prev.messages.filter((m) => m.id === replyId);
              const rest = prev.messages.filter((m) => m.id !== replyId);
              return {
                ...prev,
                messages: [...rest, { id, role: 'assistant', tool: { name: tool, status: 'running' } }, ...reply],
              };
            });
            scrollToBottom();
          },
          onToolProgress: (_tool, note) => {
            if (toolMsgId == null) return;
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) => (m.id === toolMsgId && m.tool ? { ...m, tool: { ...m.tool, note } } : m)),
            }));
          },
          onToolEnd: (_tool, ok, summary, details) => {
            const id = toolMsgId;
            toolMsgId = null;
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) =>
                m.id === id && m.tool ? { ...m, tool: { ...m.tool, status: ok ? 'done' : 'error', summary, details, note: undefined } } : m,
              ),
            }));
          },
          onStatePatch: (patch) => setToolState((s) => ({ ...s, ...patch, scanRunning: false })),
        },
      });
    } catch (err) {
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((m) =>
          m.id === replyId
            ? { ...m, thinking: false, text: m.text || `⚠️ ${err instanceof Error ? err.message : 'generation failed'}` }
            : m,
        ),
      }));
    } finally {
      // Clear any lingering thinking flag; mark an unfinished tool card stopped;
      // drop the scanRunning flag (covers a cancelled/aborted scan).
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((m) =>
          m.id === replyId
            ? { ...m, thinking: false }
            : m.id === toolMsgId && m.tool && m.tool.status === 'running'
              ? { ...m, tool: { ...m.tool, status: 'stopped', note: undefined } }
              : m,
        ),
      }));
      setToolState((s) => (s.scanRunning ? { ...s, scanRunning: false } : s));
      // Drop a reply bubble that ended up empty (e.g. a tool-only/cancelled turn).
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.filter((m) => !(m.id === replyId && !m.text && !m.steps && !m.tool)),
      }));
      setBusy(false);
      genAbort.current = null;
    }
  }

  function send() {
    const text = draft.trim();
    if (!text) return;
    setDraft('');
    void runTurn(text);
  }

  function stopGenerating() {
    genAbort.current?.abort();
  }

  // Hands-free voice MODE: the always-listening duplex controller (VAD FSM in the
  // drift wasm) drives ASR → brain → Kokoro and streams into the SAME transcript.
  async function enterVoiceMode() {
    if (brainState !== 'ready') return; // banner already prompts the download
    setMode('voice');
    setVoiceState('listening');
    const history = historyTurns(chatRef.current.messages, -1);
    try {
      const vc = await VoiceController.start(
        {
          onUserText: (text) => {
            voiceReplyId.current = null;
            setChat((prev) => ({ ...prev, messages: [...prev.messages, { id: nextId.current++, role: 'user', text }] }));
            scrollToBottom();
          },
          onAssistantToken: (tok) => {
            setChat((prev) => {
              let msgs = prev.messages;
              if (voiceReplyId.current == null) {
                const id = nextId.current++;
                voiceReplyId.current = id;
                msgs = [...msgs, { id, role: 'assistant', text: '', thinking: true }];
              }
              return {
                ...prev,
                messages: msgs.map((m) => (m.id === voiceReplyId.current ? { ...m, text: (m.text ?? '') + tok, thinking: false } : m)),
              };
            });
            scrollToBottom();
          },
          onAssistantDone: () => {
            const id = voiceReplyId.current;
            voiceReplyId.current = null;
            if (id != null) setChat((prev) => ({ ...prev, messages: prev.messages.map((m) => (m.id === id ? { ...m, thinking: false } : m)) }));
          },
          onState: (s) => setVoiceState(s),
          onLevel: (l) => {
            voiceLevel.current = l;
          },
          onToolStart: (tool) => {
            const id = nextId.current++;
            voiceToolMsgId.current = id;
            voiceReplyId.current = null; // the post-tool answer starts a fresh bubble
            if (tool === 'run_live_pr_scan') setToolState((s) => ({ ...s, scanRunning: true }));
            setChat((prev) => ({ ...prev, messages: [...prev.messages, { id, role: 'assistant', tool: { name: tool, status: 'running' } }] }));
            scrollToBottom();
          },
          onToolProgress: (_tool, note) => {
            const id = voiceToolMsgId.current;
            if (id == null) return;
            setChat((prev) => ({ ...prev, messages: prev.messages.map((m) => (m.id === id && m.tool ? { ...m, tool: { ...m.tool, note } } : m)) }));
          },
          onToolEnd: (_tool, ok, summary, details) => {
            const id = voiceToolMsgId.current;
            voiceToolMsgId.current = null;
            setToolState((s) => (s.scanRunning ? { ...s, scanRunning: false } : s));
            if (id != null)
              setChat((prev) => ({
                ...prev,
                messages: prev.messages.map((m) =>
                  m.id === id && m.tool ? { ...m, tool: { ...m.tool, status: ok ? 'done' : 'error', summary, details, note: undefined } } : m,
                ),
              }));
          },
          onStatePatch: (patch) => setToolState((s) => ({ ...s, ...patch, scanRunning: false })),
          onError: (msg) => setVoiceStatus(msg),
        },
        { persona: persona(), voice: settings.ttsVoice || 'af_heart', history, getToolState: () => toolStateRef.current },
      );
      controllerRef.current = vc;
    } catch (err) {
      setVoiceStatus(`Voice error: ${err instanceof Error ? err.message : 'unavailable'}`);
      setMode('text');
      setVoiceState('idle');
    }
  }

  async function exitVoiceMode() {
    const vc = controllerRef.current;
    controllerRef.current = null;
    setMode('text');
    setVoiceState('idle');
    voiceReplyId.current = null;
    await vc?.stop();
  }

  async function startDownload() {
    setBrainState('downloading');
    setDlProgress({ phase: 'Starting…', fraction: 0 });
    try {
      await downloadBrain((p) => setDlProgress(p));
      setBrainState('ready');
    } catch (err) {
      setDlProgress({ phase: err instanceof Error ? err.message : 'download failed', fraction: null });
      setBrainState('error');
    }
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function newChat() {
    stopStream();
    genAbort.current?.abort();
    const url = chatRef.current.url;
    setChat({ url, messages: [] });
    syncVoiceTo([]); // clear a live voice session's context too, not just the visible chat
    if (url) void clearChat(url);
    if (ctx) startReasoning(ctx);
  }

  const showDownloadBanner = brainState === 'needs-download' || brainState === 'downloading' || brainState === 'error';

  return (
    <div className="drift-app drift-root">
      <header className="app-bar">
        <span className="drift-logo" />
        <h1>{APP_NAME}</h1>
        <span className="spacer" />
        <button className="iconbtn" title="Rescan this page" onClick={() => void refresh()}>
          ↻
        </button>
        {ctx && (
          <button className="iconbtn ctx-btn" title="Loaded context" onClick={onOpenContext}>
            📎<span className="ctx-btn-count">{ctx.artifacts.length}</span>
          </button>
        )}
        <button className="iconbtn" title="New chat" onClick={newChat} disabled={messages.length === 0}>
          ＋
        </button>
        <button
          className="iconbtn"
          title="Live pipeline — run the scan + render the PR comment here (no AI)"
          onClick={onOpenPipeline}
        >
          ⚡
        </button>
        <button className="iconbtn" title="Settings" onClick={onOpenSettings}>
          ⚙
        </button>
      </header>

      {toolState.pr && (
        <div className="pr-chip">
          <a
            className="pr-chip-link"
            href={toolState.url ?? undefined}
            target="_blank"
            rel="noreferrer"
            title={toolState.title ?? undefined}
          >
            {toolState.pr.repo}#{toolState.pr.number}
          </a>
          <span className={`pr-chip-scan ${toolState.scanRunning ? 'running' : toolState.scanRan ? 'done' : 'none'}`}>
            {toolState.scanRunning
              ? '● scanning…'
              : toolState.scanRan
                ? `✓ scanned${toolState.changedCount != null ? ` · ${toolState.changedCount} file(s)` : ''}`
                : '○ not scanned'}
          </span>
          {toolState.scanRunning && (
            <button className="pr-chip-stop" onClick={stopGenerating} title="Stop the scan">
              ■ Stop
            </button>
          )}
        </div>
      )}

      {showDownloadBanner && (
        <div className="brain-banner">
          {brainState === 'downloading' ? (
            <>
              <span className="spinner" />
              <span className="brain-banner-text">{dlProgress?.phase ?? 'Downloading AI model…'}</span>
              {dlProgress?.fraction != null && (
                <span className="brain-banner-pct">{Math.round(dlProgress.fraction * 100)}%</span>
              )}
            </>
          ) : brainState === 'error' ? (
            <>
              <span className="brain-banner-text">⚠️ {dlProgress?.phase ?? 'Download failed'}</span>
              <button className="brain-banner-btn" onClick={startDownload}>
                Retry
              </button>
            </>
          ) : (
            <>
              <span className="brain-banner-text">Download the on-device AI model to start chatting (~1.1 GB, one time).</span>
              <button className="brain-banner-btn" onClick={startDownload}>
                Download AI model
              </button>
            </>
          )}
        </div>
      )}

      <div className="chat-scroll" ref={scrollRef}>
        {messages.length === 0 ? (
          <div className="chat-empty">
            <div className="mark" />
            <h2>How can I help?</h2>
            <p>Ask about the PR or file you’re viewing. Use “/” for commands.</p>
          </div>
        ) : (
          messages.map((m) =>
            m.tool ? (
              <ToolStep key={m.id} tool={m.tool} />
            ) : m.steps ? (
              <ReasoningTurn
                key={m.id}
                title={m.title}
                steps={m.steps}
                thinking={!!m.thinking}
                files={ctx?.artifacts}
                onOpenFile={setModalFile}
              />
            ) : (
              <div key={m.id} className={`msg ${m.role}`}>
                <div className={`bubble ${m.role === 'assistant' ? 'muted' : ''}`}>
                  {m.text}
                  {m.thinking && <span className="cursor">▌</span>}
                </div>
              </div>
            ),
          )
        )}
        {/* Spoken summary, when the PR's comment linked one — playable inline. */}
        {ctx?.audio && messages.length > 0 && <AudioSummary audio={ctx.audio} />}
      </div>

      {mode === 'voice' ? (
        <div className="voice-panel">
          <VoiceOrb mode={voiceState} levelRef={voiceLevel} height={248} />
          <div className="voice-state-label">
            {voiceState === 'listening'
              ? 'Listening…'
              : voiceState === 'thinking'
                ? 'Thinking…'
                : voiceState === 'speaking'
                  ? 'Speaking…'
                  : 'Starting…'}
          </div>
          {voiceStatus && <div className="voice-substatus">{voiceStatus}</div>}
          <button className="voice-exit" onClick={() => void exitVoiceMode()}>
            End voice mode
          </button>
        </div>
      ) : (
      <div className="composer">
        <div className="composer-box">
          {ctx && (
            <div className="attach-row">
              {ctx.artifacts.map((a) => (
                <button
                  key={a.url ?? a.name}
                  className="attach-chip"
                  onClick={() => setModalFile(a)}
                  title={`Open ${a.name}`}
                >
                  <FileIcon size={16} />
                  <span className="attach-name">{a.name}</span>
                </button>
              ))}
            </div>
          )}
          <textarea
            rows={1}
            placeholder={brainState === 'unsupported' ? 'On-device AI needs WebGPU (unavailable here)' : 'Type / for commands'}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={onKeyDown}
          />
          <div className="composer-row">
            <button
              className="ask-toggle"
              data-on={settings.askBeforeActing}
              onClick={() => void patchSettings({ askBeforeActing: !settings.askBeforeActing })}
              title="Toggle whether actions need confirmation"
            >
              {settings.askBeforeActing ? '✋ Ask before acting' : '⚡ Act automatically'}
            </button>
            {voiceStatus && <span className="voice-status">{voiceStatus}</span>}
            <button
              className="mic"
              onClick={() => void enterVoiceMode()}
              disabled={brainState !== 'ready' || busy}
              title="Hands-free voice mode"
            >
              🎙
            </button>
            {busy ? (
              <button className="send stop" onClick={stopGenerating} title="Stop">
                ■
              </button>
            ) : (
              <button className="send" onClick={send} disabled={!draft.trim()} title="Send">
                ↑
              </button>
            )}
          </div>
        </div>
        <div className="composer-foot">{APP_NAME} is AI and can make mistakes.</div>
      </div>
      )}

      {modalFile && <FileModal artifact={modalFile} onClose={() => setModalFile(null)} />}
    </div>
  );
}

/** Human labels for the agent's tools, for the tool-step card. The specialized
 *  agents contribute their own `label` (single source of truth in agents/lenses.ts)
 *  so a card never shows a raw underscored tool id. */
const TOOL_LABELS: Record<string, string> = {
  run_live_pr_scan: 'Running PR scan',
  list_changed_files: 'Listing changed files',
  get_pr_architecture: 'Mapping architecture',
  explain_architecture: 'Reading the code',
  ...Object.fromEntries(LENSES.map((l) => [l.id, l.label])),
};

function ToolStep({ tool }: { tool: NonNullable<ChatMessage['tool']> }) {
  const [copied, setCopied] = useState(false);
  const label = TOOL_LABELS[tool.name] ?? tool.name;
  const icon =
    tool.status === 'running' ? <span className="spinner" /> : tool.status === 'done' ? '✓' : tool.status === 'stopped' ? '■' : '✗';
  // On failure we captured a developer report (error + context + progress log).
  // Offer it as a one-click copy so it can be pasted into a bug report.
  const copyDetails = () => {
    if (!tool.details) return;
    void navigator.clipboard.writeText(tool.details).then(
      () => {
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      },
      () => {},
    );
  };
  return (
    <div className={`tool-step ${tool.status}`}>
      <span className="tool-step-icon">{icon}</span>
      <span className="tool-step-label">{label}</span>
      {tool.status === 'running' && tool.note && <span className="tool-step-note">{tool.note}</span>}
      {tool.status !== 'running' && tool.summary && <span className="tool-step-summary">{tool.summary}</span>}
      {tool.status === 'error' && tool.details && (
        <button className="tool-step-copy" onClick={copyDetails} title="Copy the error and logs for developers">
          {copied ? 'Copied' : 'Copy details'}
        </button>
      )}
    </div>
  );
}

function ReasoningTurn({
  title,
  steps,
  thinking,
  files,
  onOpenFile,
}: {
  title?: string;
  steps: ReasoningStep[];
  thinking: boolean;
  files?: ArtifactRef[];
  onOpenFile?: (a: ArtifactRef) => void;
}) {
  return (
    <div className="reasoning">
      <div className="reasoning-head">
        {thinking ? <span className="spinner" /> : <span className="reasoning-check">✓</span>}
        <span>{thinking ? title ?? 'Thinking…' : title ?? 'Reasoned'}</span>
      </div>
      <ol className="reasoning-steps">
        {steps.map((s, i) => (
          <li key={i} className={`rs-${s.level}`}>
            {s.text}
          </li>
        ))}
        {thinking && (
          <li className="rs-typing">
            <span className="dot" />
            <span className="dot" />
            <span className="dot" />
          </li>
        )}
      </ol>
      {!thinking && files && files.length > 0 && (
        <div className="reasoning-files">
          <span className="rfiles-label">Download:</span>
          {files.map((f) => (
            <button key={f.url ?? f.name} className="rfile-btn" onClick={() => onOpenFile?.(f)}>
              <FileIcon size={14} />
              <span>{f.name}</span>
              <span className="rfile-dl">⬇</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
