import { useEffect, useRef, useState } from 'react';
import { APP_NAME } from '../config';
import { patchSettings, type Settings } from '../state/settings';
import { usePrContext } from '../state/prContext';
import { FileModal } from './FileModal';
import { FileIcon } from './FileIcon';
import { AudioSummary } from './AudioSummary';
import { buildReasoning, reasoningTitle, type ReasoningStep } from './reasoning';
import { getChat, saveChat, clearChat, type ChatMessage } from '../state/chatHistory';
import type { ArtifactRef, PrContext } from '../core/types';
import { type Turn } from '../core/chatContext';
import { DEFAULT_PERSONA } from '../core/brainConstants';
import { getSharedBrain } from '../core/brainEngine';
import { isBrainSupported } from '../core/brainRuntime';
import { downloadBrain, isBrainAvailable, type AcquireProgress } from '../core/brainStore';
import { VoiceController, type VoiceState, type VoiceHandlers } from '../core/voiceController';
import { startGeminiLive, type VoiceSession } from '../core/geminiLiveController';
import { VoiceOrb } from './VoiceOrb';
import { useActivePr } from '../state/activePr';
import { runAgentTurn } from '../core/agentLoop';
import { EMPTY_PR_STATE, type PrToolState } from '../core/chatTools';
import { LENSES } from '../agents/lenses';
import { latestScanForPr, prUrl } from '../core/runLiveScan';
import { hasHandoverSession, clearHandoverSession } from '../state/handoverSession';
import { runScrollPlanThroughFile } from '../core/prNavigate';
import type { FilePresentation, PresentBeat } from '../agents/scrollPlan';
import { ChangeImpactGraph } from './report/ChangeImpactGraph';
import {
  beatAtElapsed,
  beatStartOffsets,
  clockElapsed,
  fmtClock,
  planDurationMs,
  type MediaClock,
} from '../agents/presentationClock';

const STEP_INTERVAL_MS = 450;

/** Brain lifecycle as the chat sees it. */
// 'needs-download' = the on-device model must be downloaded; 'needs-setup' = a remote/local
// provider (Gemini / Ollama) isn't configured yet (no download — set it up in Settings).
type BrainState = 'checking' | 'unsupported' | 'needs-download' | 'needs-setup' | 'downloading' | 'ready' | 'error';

// The chat surface. Conversations are persisted per PR url (chat history), so
// revisiting a PR restores its conversation instantly. The reply is generated by
// the in-browser LLM brain (Qwen via WebLLM) — tokens stream into a live bubble.
export function Chat({
  settings,
  onOpenSettings,
  onOpenContext,
  onOpenPipeline,
}: {
  settings: Settings;
  onOpenSettings: () => void;
  onOpenContext: () => void;
  onOpenPipeline: () => void;
}) {
  // The conversation is bound to a PR url so persistence is always atomic.
  const [chat, setChat] = useState<{ url: string | null; messages: ChatMessage[] }>({
    url: null,
    messages: [],
  });
  const messages = chat.messages;
  const [draft, setDraft] = useState('');
  const [modalFile, setModalFile] = useState<ArtifactRef | null>(null);
  const [brainState, setBrainState] = useState<BrainState>('checking');
  const [dlProgress, setDlProgress] = useState<AcquireProgress | null>(null);
  const [busy, setBusy] = useState(false);
  const [voiceStatus, setVoiceStatus] = useState<string | null>(null);
  const [mode, setMode] = useState<'text' | 'voice'>('text');
  const [voiceState, setVoiceState] = useState<VoiceState>('idle');
  // Which file-presentation beat is currently "on screen" — the chat lights up THAT
  // button in lockstep with the page scroll. Driven by the ONE timeline media-clock
  // below. Ephemeral UI state (msgId scopes it to the right message); never persisted.
  const [activeBeat, setActiveBeat] = useState<{ msgId: number; index: number } | null>(null);
  const activeBeatRef = useRef(activeBeat);
  activeBeatRef.current = activeBeat;
  // Where a MANUAL page-scroll paused the walkthrough — so the reviewer can RESUME from
  // that spot (the page scroller messages us when a human grabs the scroll).
  const [pausedBeat, setPausedBeat] = useState<{ msgId: number; index: number } | null>(null);
  // THE timeline media-clock — the SINGLE source of truth for playback. As it counts it
  // moves the playhead AND (via the rAF driver below) advances the active section + the
  // page scroll, so the timeline, the buttons, and the page navigate together.
  const [playhead, setPlayhead] = useState<({ msgId: number; mode: 'text' | 'voice' } & MediaClock) | null>(null);
  // Which message's presentation is currently playing (its beats + anchor for the driver,
  // and so the page→panel "user scrolled" signal pauses the right message at its spot).
  const playingRef = useRef<{ msgId: number; pres: FilePresentation } | null>(null);
  const controllerRef = useRef<VoiceSession | null>(null);
  const voiceReplyId = useRef<number | null>(null);
  const voiceToolMsgId = useRef<number | null>(null); // current tool-step card id in voice mode
  const voicePresentation = useRef<FilePresentation | null>(null); // beats awaiting the spoken reply bubble
  const voiceLevel = useRef(0); // 0..1 energy for the orb (written per audio frame, never setState)
  const nextId = useRef(1);
  const scrollRef = useRef<HTMLDivElement>(null);
  const chatRef = useRef(chat);
  chatRef.current = chat;
  const targetUrl = useRef<string | null>(null);
  const streamIv = useRef<number | null>(null);
  const genAbort = useRef<AbortController | null>(null);
  const { ctx, refresh } = usePrContext();
  const activePr = useActivePr();

  // PR/scan tool state — surfaced in the chip AND injected into the agent prompt.
  // `scanRan`/`changedCount` seed from history; `scanRunning` flips during a tool.
  const [toolState, setToolState] = useState<PrToolState>(EMPTY_PR_STATE);
  const toolStateRef = useRef(toolState);
  toolStateRef.current = toolState;

  // Recompute tool state when the active PR changes: read the latest scan from
  // history (cache, no network) so "scan ran" + file count are known up front.
  // Keyed ONLY on the PR identity (owner/repo/number) — NOT ctx.pr.title, which goes
  // undefined on the /files & /changes sub-pages and would otherwise RESET scan_ran +
  // handover_active to false (breaking handover routing) until the async re-fetch
  // healed it. The title is patched in separately below.
  useEffect(() => {
    let alive = true;
    if (!activePr) {
      setToolState(EMPTY_PR_STATE);
      return;
    }
    const url = prUrl(activePr);
    setToolState({
      pr: activePr,
      url,
      title: ctx?.pr.title ?? null,
      scanRan: false,
      scanRunning: false,
      changedCount: null,
      architectureKnown: false,
      handoverActive: false,
    });
    void latestScanForPr(activePr).then((rec) => {
      if (!alive || !rec) return;
      setToolState((s) => ({ ...s, scanRan: true, changedCount: rec.changedFiles ?? null }));
    });
    // Resume a handover walkthrough if one is saved for this PR (survives reloads
    // + tab switches), so "next"/"resume" deterministically route back into it.
    void hasHandoverSession(url).then((active) => {
      if (alive && active) setToolState((s) => ({ ...s, handoverActive: true }));
    });
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activePr?.owner, activePr?.repo, activePr?.number]);

  // Patch in the PR title once the report scrape (ctx) lands, without resetting the
  // rest of the tool state (so navigating to a sub-page never drops scan/handover).
  useEffect(() => {
    if (ctx?.pr.title) setToolState((s) => (s.pr && s.title !== ctx.pr.title ? { ...s, title: ctx.pr.title } : s));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx?.pr.title]);

  const scrollToBottom = () => {
    requestAnimationFrame(() => {
      scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    });
  };

  const stopStream = () => {
    if (streamIv.current != null) {
      window.clearInterval(streamIv.current);
      streamIv.current = null;
    }
  };

  // Halt the chat-side follow (the rAF driver stops when the playhead is cleared/paused).
  // The page scroller independently self-cancels on a manual scroll.
  const stopPresentation = () => {
    playingRef.current = null;
  };

  // Scroll + highlight ONE beat on the GitHub page (a single-beat plan, so the page
  // doesn't run its own multi-beat timer — the timeline clock decides when to advance).
  // ALWAYS 'text' (zero lead): the media clock already owns the timing — including the
  // one-time voice lead before beat 0 (beatStartOffsets) — so a per-beat voice lead here
  // would re-apply 700ms on EVERY beat, making the page highlight lag the chat highlight.
  const scrollPageToBeat = (pres: FilePresentation, index: number) => {
    const b = pres.beats[index];
    if (b) void runScrollPlanThroughFile(pres.anchorId, pres.path, [b], 'text');
  };

  // Start the ONE timeline media-clock that drives the whole walkthrough — the moving
  // playhead, the active section, and the page scroll all come off this (the rAF driver
  // below ticks it). `baseMs` is where the playhead starts (a spot's offset / elapsed).
  const startPlayhead = (msgId: number, pres: FilePresentation, mode: 'text' | 'voice', baseMs: number) => {
    playingRef.current = { msgId, pres };
    setPausedBeat(null);
    setActiveBeat({ msgId, index: beatAtElapsed(pres.beats, mode, Math.max(0, baseMs)).index });
    setPlayhead({ msgId, mode, totalMs: planDurationMs(pres.beats, mode), baseMs: Math.max(0, baseMs), runningSince: Date.now() });
  };

  // TEXT auto-play / click. The page scroll for text is driven by the handover's in-page
  // scroller (auto) or a click's plan; the timeline clock drives the active section +
  // playhead in lockstep. Auto-play re-syncs to where the page already is via `startedAt`.
  const playPresentation = (msgId: number, pres: FilePresentation, opts: { fromIndex?: number; drivePage?: boolean }) => {
    stopPresentation();
    if (!pres.beats.length) return;
    const drivePage = !!opts.drivePage;
    const from = Math.min(Math.max(0, opts.fromIndex ?? 0), pres.beats.length - 1);
    if (drivePage) void runScrollPlanThroughFile(pres.anchorId, pres.path, pres.beats.slice(from), 'text');
    const elapsedMs = !drivePage && pres.startedAt != null ? Math.max(0, Date.now() - pres.startedAt) : undefined;
    startPlayhead(msgId, pres, 'text', elapsedMs ?? beatStartOffsets(pres.beats, 'text')[from] ?? 0);
  };

  // VOICE. The timeline clock (paced to speaking speed) drives EVERYTHING — the active
  // section, the moving playhead, AND the page scroll (the handover doesn't scroll in
  // voice) — so the page navigates smoothly and automatically as the timeline counts.
  const startVoiceFollow = (msgId: number, pres: FilePresentation, fromIndex = 0) => {
    stopPresentation();
    if (!pres.beats.length) return;
    const from = Math.min(Math.max(0, fromIndex), pres.beats.length - 1);
    startPlayhead(msgId, pres, 'voice', beatStartOffsets(pres.beats, 'voice')[from] ?? 0);
  };

  // THE single playback driver. While the media-clock runs, each animation frame maps the
  // elapsed time → the current beat; when it crosses into a new spot it lights that
  // section's button AND (in voice) scrolls the page there — so the timeline, the inline
  // buttons, and the page navigate together, smoothly and automatically. Stops + parks at
  // the end. Re-runs only when the clock changes (play / pause / seek), not per frame.
  useEffect(() => {
    const ph = playhead;
    if (!ph || ph.runningSince == null) return;
    let raf = 0;
    let lastIdx = -1;
    const tick = () => {
      const playing = playingRef.current;
      if (!playing || playing.msgId !== ph.msgId) return; // superseded / stopped
      const elapsed = clockElapsed(ph, Date.now());
      const { index } = beatAtElapsed(playing.pres.beats, ph.mode, elapsed);
      if (index !== lastIdx) {
        lastIdx = index;
        setActiveBeat({ msgId: ph.msgId, index });
        // Voice: drive the page scroll here (the handover doesn't, in voice). Text: the
        // handover's in-page scroller already walks the file — don't double-drive it.
        if (ph.mode === 'voice') scrollPageToBeat(playing.pres, index);
      }
      if (elapsed >= ph.totalMs) {
        // Reached the end → park the clock (freezes the playhead, stops the rAFs).
        setPlayhead((p) => (p && p.msgId === ph.msgId ? { ...p, baseMs: p.totalMs, runningSince: null } : p));
        return;
      }
      raf = requestAnimationFrame(tick);
    };
    tick();
    return () => cancelAnimationFrame(raf);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playhead]);

  // A click on a beat button — jump there and proceed (voice keeps following speech;
  // text resumes the reading clock).
  const onBeatClick = (msgId: number, pres: FilePresentation, index: number) => {
    if (mode === 'voice') startVoiceFollow(msgId, pres, index);
    else playPresentation(msgId, pres, { fromIndex: index, drivePage: true });
  };

  // Resume a walkthrough a manual page-scroll paused — from the remembered spot.
  const resumePresentation = () => {
    const p = pausedBeat;
    if (!p) return;
    const pres = chatRef.current.messages.find((m) => m.id === p.msgId)?.presentation;
    if (pres) onBeatClick(p.msgId, pres, p.index);
  };

  // The page scroller tells us when the reviewer manually grabbed the scroll mid-
  // walkthrough → PAUSE the follow and REMEMBER the spot so they can resume from it
  // (or click another). Matched to whichever presentation is currently playing.
  useEffect(() => {
    if (typeof chrome === 'undefined' || !chrome.runtime?.onMessage) return;
    const onMsg = (msg: unknown) => {
      const m = msg as { type?: string; anchorId?: string };
      if (m?.type !== 'drift:present-interrupted') return;
      const playing = playingRef.current;
      if (!playing || playing.pres.anchorId !== m.anchorId) return;
      const at = activeBeatRef.current;
      const index = at?.msgId === playing.msgId ? at.index : 0;
      stopPresentation();
      setPausedBeat({ msgId: playing.msgId, index });
      // Freeze the timeline playhead where it stopped (so Resume picks up from here).
      setPlayhead((p) => (p && p.msgId === playing.msgId ? { ...p, baseMs: clockElapsed(p, Date.now()), runningSince: null } : p));
    };
    chrome.runtime.onMessage.addListener(onMsg);
    return () => chrome.runtime.onMessage.removeListener(onMsg);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Probe the brain when the provider changes. WebGPU is required only for the on-device
  // 'local' brain; Gemini/Ollama are "ready" once configured (no download). The mode comes
  // from the reactive `settings` prop (no extra async read), and re-probes when it changes.
  useEffect(() => {
    let alive = true;
    const mode = settings.brainMode ?? 'local';
    (async () => {
      if (mode === 'local' && !(await isBrainSupported())) {
        if (alive) setBrainState('unsupported');
        return;
      }
      const ready = await isBrainAvailable();
      if (alive) setBrainState(ready ? 'ready' : mode === 'local' ? 'needs-download' : 'needs-setup');
    })();
    return () => {
      alive = false;
    };
  }, [settings.brainMode]);

  // Stream the step-by-step reasoning turn for a freshly-detected PR.
  function startReasoning(c: PrContext) {
    const allSteps = buildReasoning(c);
    const id = nextId.current++;
    setChat((prev) =>
      prev.messages.some((x) => x.steps && x.prUrl === c.pr.url)
        ? prev
        : {
            ...prev,
            messages: [
              ...prev.messages,
              { id, role: 'assistant', title: reasoningTitle(c), steps: [], thinking: true, prUrl: c.pr.url },
            ],
          },
    );
    let shown = 0;
    stopStream();
    streamIv.current = window.setInterval(() => {
      shown += 1;
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((x) =>
          x.id === id ? { ...x, steps: allSteps.slice(0, shown), thinking: shown < allSteps.length } : x,
        ),
      }));
      scrollToBottom();
      if (shown >= allSteps.length) stopStream();
    }, STEP_INTERVAL_MS);
  }

  // Switch conversation when the active PR changes: persist the outgoing one,
  // restore the incoming one from storage (instant), or stream it fresh.
  //
  // KEYED ON activePr (the tab-URL PR identity), NOT the scraped `ctx`. `ctx` goes
  // NULL on a PR's /files & /changes sub-pages (the Drift comment it scrapes lives
  // only on the Conversation tab) — and the handover navigates the tab THERE — so
  // keying on ctx wiped the whole conversation (and reset the voice context)
  // mid-walkthrough. activePr is stable across a PR's sub-pages, so /pull/N →
  // /pull/N/files is a no-op here and the conversation persists.
  const convoUrl = activePr ? prUrl(activePr) : null;
  useEffect(() => {
    const url = convoUrl;
    if (url === chatRef.current.url) return;
    targetUrl.current = url;
    stopPresentation(); // leaving this PR halts its walkthrough highlight
    setActiveBeat(null);
    setPausedBeat(null);
    setPlayhead(null);

    const prev = chatRef.current;
    if (prev.url && prev.messages.length) void saveChat(prev.url, prev.messages);
    stopStream();

    if (!url) {
      setChat({ url, messages: [] });
      syncVoiceTo([]); // left every PR — drop the old PR's voice context
      return;
    }
    void getChat(url).then((saved) => {
      if (targetUrl.current !== url) return; // navigated again — drop stale load
      if (saved.length) {
        nextId.current = Math.max(0, ...saved.map((m) => m.id)) + 1;
        setChat({ url, messages: saved }); // instant restore — no re-stream
        syncVoiceTo(historyTurns(saved, -1));
      } else {
        setChat({ url, messages: [] });
        syncVoiceTo([]);
        if (ctx && ctx.pr.url === url) startReasoning(ctx); // intro only if the report is already scraped
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [convoUrl]);

  // The scraped report (ctx) usually lands a beat AFTER activePr. If it arrives for
  // the current, still-empty conversation, stream the reasoning intro then. (No-op
  // when ctx is null — e.g. on the /files sub-page — so it never clears anything.)
  useEffect(() => {
    if (ctx && ctx.pr.url === chatRef.current.url && chatRef.current.messages.length === 0) {
      startReasoning(ctx);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx?.pr.url]);

  // Persist the conversation (debounced) under its PR url.
  useEffect(() => {
    if (!chat.url) return;
    const t = window.setTimeout(() => void saveChat(chat.url!, chat.messages), 500);
    return () => window.clearTimeout(t);
  }, [chat]);

  // Stop any running stream / generation when the panel unmounts.
  useEffect(
    () => () => {
      stopStream();
      genAbort.current?.abort();
      stopPresentation();
      void controllerRef.current?.stop();
    },
    [],
  );

  // Build the persona, grounding it in the active PR when one is loaded.
  function persona(): string {
    const base = settings.persona?.trim() || DEFAULT_PERSONA;
    if (!ctx) return base;
    return `${base}\n\nContext: the user is viewing pull request ${ctx.pr.repo}#${ctx.pr.number} — "${ctx.pr.title ?? ''}". Ground your answers in this PR when relevant.`;
  }

  // Re-ground a LIVE voice session on a new conversation (PR switch / new chat).
  // The controller captured the old PR's persona + context at start and lives
  // across navigation, so without this it keeps talking about the old PR. No-op
  // in text mode (no controller).
  function syncVoiceTo(history: Turn[]) {
    const vc = controllerRef.current;
    if (!vc) return;
    voiceReplyId.current = null;
    voiceToolMsgId.current = null;
    vc.resetConversation(persona(), history);
  }

  // Project the visible transcript into chat turns for the brain (skip reasoning
  // steps — they have no plain text — and the live placeholder being filled).
  function historyTurns(msgs: ChatMessage[], skipId: number): Turn[] {
    const turns: Turn[] = [];
    for (const m of msgs) {
      if (m.id === skipId || m.steps || !m.text) continue;
      turns.push({ role: m.role === 'assistant' ? 'agent' : 'user', text: m.text });
    }
    return turns;
  }

  // One conversational turn: append the user message + a live assistant bubble,
  // then stream tokens from the brain into it. Shared by text send + voice mode.
  async function runTurn(userText: string) {
    const text = userText.trim();
    if (!text || busy) return;
    stopPresentation(); // a new turn interrupts any running walkthrough highlight
    if (brainState !== 'ready') {
      // No brain — surface the reason instead of pretending to answer.
      setChat((prev) => ({
        ...prev,
        messages: [
          ...prev.messages,
          { id: nextId.current++, role: 'user', text },
          {
            id: nextId.current++,
            role: 'assistant',
            text:
              brainState === 'unsupported'
                ? 'This browser has no WebGPU, so the on-device AI can’t run here. You can switch to Gemini or a local Ollama in Settings.'
                : brainState === 'needs-setup'
                  ? 'Finish setting up your AI provider in Settings (pick an Ollama model, or add a Gemini key).'
                  : 'Download the AI model first (Settings → Download AI model).',
          },
        ],
      }));
      scrollToBottom();
      return;
    }

    const userMsg: ChatMessage = { id: nextId.current++, role: 'user', text };
    const replyId = nextId.current++;
    const replyMsg: ChatMessage = { id: replyId, role: 'assistant', text: '', thinking: true };
    setChat((prev) => ({ ...prev, messages: [...prev.messages, userMsg, replyMsg] }));
    scrollToBottom();

    const prior = historyTurns(chatRef.current.messages, replyId);

    const abort = new AbortController();
    genAbort.current = abort;
    setBusy(true);
    // Track the tool-step card id for the in-flight tool (one at a time).
    let toolMsgId: number | null = null;
    try {
      const brain = await getSharedBrain();
      await runAgentTurn({
        brain,
        persona: persona(),
        history: prior,
        userText: text,
        getState: () => toolStateRef.current,
        signal: abort.signal,
        events: {
          onToken: (delta) => {
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) =>
                m.id === replyId ? { ...m, text: (m.text ?? '') + delta, thinking: false } : m,
              ),
            }));
            scrollToBottom();
          },
          onToolStart: (tool) => {
            const id = nextId.current++;
            toolMsgId = id;
            setToolState((s) => ({ ...s, scanRunning: tool === 'run_live_pr_scan' ? true : s.scanRunning }));
            // Insert the tool-step card BEFORE the (still-empty) reply bubble.
            setChat((prev) => {
              const reply = prev.messages.filter((m) => m.id === replyId);
              const rest = prev.messages.filter((m) => m.id !== replyId);
              return {
                ...prev,
                messages: [...rest, { id, role: 'assistant', tool: { name: tool, status: 'running' } }, ...reply],
              };
            });
            scrollToBottom();
          },
          onToolProgress: (_tool, note) => {
            if (toolMsgId == null) return;
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) => (m.id === toolMsgId && m.tool ? { ...m, tool: { ...m.tool, note } } : m)),
            }));
          },
          onToolEnd: (_tool, ok, summary, details) => {
            const id = toolMsgId;
            toolMsgId = null;
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) =>
                m.id === id && m.tool ? { ...m, tool: { ...m.tool, status: ok ? 'done' : 'error', summary, details, note: undefined } } : m,
              ),
            }));
          },
          onStatePatch: (patch) => setToolState((s) => ({ ...s, ...patch, scanRunning: false })),
          onPresentation: (presentation) => {
            setChat((prev) => ({
              ...prev,
              messages: prev.messages.map((m) => (m.id === replyId ? { ...m, presentation } : m)),
            }));
            // Auto-play the synchronized chat highlight alongside the page scroll the
            // handover already started (reading pace). Clicking a beat re-seeks both.
            playPresentation(replyId, presentation, { drivePage: false });
          },
        },
      });
    } catch (err) {
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((m) =>
          m.id === replyId
            ? { ...m, thinking: false, text: m.text || `⚠️ ${err instanceof Error ? err.message : 'generation failed'}` }
            : m,
        ),
      }));
    } finally {
      // Clear any lingering thinking flag; mark an unfinished tool card stopped;
      // drop the scanRunning flag (covers a cancelled/aborted scan).
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.map((m) =>
          m.id === replyId
            ? { ...m, thinking: false }
            : m.id === toolMsgId && m.tool && m.tool.status === 'running'
              ? { ...m, tool: { ...m.tool, status: 'stopped', note: undefined } }
              : m,
        ),
      }));
      setToolState((s) => (s.scanRunning ? { ...s, scanRunning: false } : s));
      // Drop a reply bubble that ended up empty (e.g. a tool-only/cancelled turn).
      setChat((prev) => ({
        ...prev,
        messages: prev.messages.filter((m) => !(m.id === replyId && !m.text && !m.steps && !m.tool)),
      }));
      setBusy(false);
      genAbort.current = null;
    }
  }

  function send() {
    const text = draft.trim();
    if (!text) return;
    setDraft('');
    void runTurn(text);
  }

  function stopGenerating() {
    genAbort.current?.abort();
  }

  // Hands-free voice MODE: the always-listening duplex controller (VAD FSM in the
  // drift wasm) drives ASR → brain → Kokoro and streams into the SAME transcript.
  async function enterVoiceMode() {
    if (brainState !== 'ready') return; // banner already prompts the download
    setMode('voice');
    setVoiceState('listening');
    const history = historyTurns(chatRef.current.messages, -1);
    try {
      // Pick the voice engine for the selected brain: Gemini Live (native audio,
      // server-side turn-taking — replaces Whisper+Kokoro) or the local duplex
      // cascade. Both satisfy VoiceSession and take the SAME handlers, so the
      // whole transcript-wiring object below is shared verbatim.
      const startVoice = (h: VoiceHandlers): Promise<VoiceSession> =>
        settings.brainMode === 'gemini-live'
          ? startGeminiLive(h, { apiKey: settings.geminiApiKey ?? '', model: settings.geminiLiveModel, persona: persona(), getToolState: () => toolStateRef.current })
          : VoiceController.start(h, { persona: persona(), voice: settings.ttsVoice || 'af_heart', history, getToolState: () => toolStateRef.current });
      const vc = await startVoice(
        {
          onUserText: (text) => {
            stopPresentation(); // the reviewer spoke — interrupt the running walkthrough
            voiceReplyId.current = null;
            setChat((prev) => ({ ...prev, messages: [...prev.messages, { id: nextId.current++, role: 'user', text }] }));
            scrollToBottom();
          },
          onAssistantToken: (tok) => {
            if (voiceReplyId.current == null) {
              // First token of a reply → open the bubble. Resolve the id + presentation
              // SYNCHRONOUSLY (not inside the setState updater, which React may defer — that
              // left `startVoiceFollow` never called, so the timeline never auto-started).
              const id = nextId.current++;
              voiceReplyId.current = id;
              const pres = voicePresentation.current ?? undefined;
              voicePresentation.current = null;
              setChat((prev) => ({ ...prev, messages: [...prev.messages, { id, role: 'assistant', text: tok, thinking: false, presentation: pres }] }));
              if (pres) startVoiceFollow(id, pres); // auto-start the timeline-driven walkthrough
            } else {
              const id = voiceReplyId.current;
              setChat((prev) => ({
                ...prev,
                messages: prev.messages.map((m) => (m.id === id ? { ...m, text: (m.text ?? '') + tok, thinking: false } : m)),
              }));
            }
            scrollToBottom();
          },
          onPresentation: (presentation) => {
            // The handover beats can arrive BEFORE the spoken bubble exists — stash them
            // (onAssistantToken attaches + plays them). If a bubble is already open,
            // attach + start the synchronized highlight now.
            if (voiceReplyId.current == null) {
              voicePresentation.current = presentation;
            } else {
              const id = voiceReplyId.current;
              setChat((prev) => ({
                ...prev,
                messages: prev.messages.map((m) => (m.id === id ? { ...m, presentation } : m)),
              }));
              startVoiceFollow(id, presentation);
            }
          },
          onAssistantDone: () => {
            const id = voiceReplyId.current;
            voiceReplyId.current = null;
            if (id != null) setChat((prev) => ({ ...prev, messages: prev.messages.map((m) => (m.id === id ? { ...m, thinking: false } : m)) }));
          },
          onState: (s) => setVoiceState(s),
          onLevel: (l) => {
            voiceLevel.current = l;
          },
          onToolStart: (tool) => {
            const id = nextId.current++;
            voiceToolMsgId.current = id;
            voiceReplyId.current = null; // the post-tool answer starts a fresh bubble
            if (tool === 'run_live_pr_scan') setToolState((s) => ({ ...s, scanRunning: true }));
            setChat((prev) => ({ ...prev, messages: [...prev.messages, { id, role: 'assistant', tool: { name: tool, status: 'running' } }] }));
            scrollToBottom();
          },
          onToolProgress: (_tool, note) => {
            const id = voiceToolMsgId.current;
            if (id == null) return;
            setChat((prev) => ({ ...prev, messages: prev.messages.map((m) => (m.id === id && m.tool ? { ...m, tool: { ...m.tool, note } } : m)) }));
          },
          onToolEnd: (_tool, ok, summary, details) => {
            const id = voiceToolMsgId.current;
            voiceToolMsgId.current = null;
            setToolState((s) => (s.scanRunning ? { ...s, scanRunning: false } : s));
            if (id != null)
              setChat((prev) => ({
                ...prev,
                messages: prev.messages.map((m) =>
                  m.id === id && m.tool ? { ...m, tool: { ...m.tool, status: ok ? 'done' : 'error', summary, details, note: undefined } } : m,
                ),
              }));
          },
          onStatePatch: (patch) => setToolState((s) => ({ ...s, ...patch, scanRunning: false })),
          onError: (msg) => setVoiceStatus(msg),
        },
      );
      controllerRef.current = vc;
    } catch (err) {
      setVoiceStatus(`Voice error: ${err instanceof Error ? err.message : 'unavailable'}`);
      setMode('text');
      setVoiceState('idle');
    }
  }

  async function exitVoiceMode() {
    const vc = controllerRef.current;
    controllerRef.current = null;
    stopPresentation();
    setActiveBeat(null);
    setPausedBeat(null);
    setPlayhead(null);
    setMode('text');
    setVoiceState('idle');
    voiceReplyId.current = null;
    await vc?.stop();
  }

  async function startDownload() {
    setBrainState('downloading');
    setDlProgress({ phase: 'Starting…', fraction: 0 });
    try {
      await downloadBrain((p) => setDlProgress(p));
      setBrainState('ready');
    } catch (err) {
      setDlProgress({ phase: err instanceof Error ? err.message : 'download failed', fraction: null });
      setBrainState('error');
    }
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function newChat() {
    stopStream();
    genAbort.current?.abort();
    stopPresentation();
    setActiveBeat(null);
    setPausedBeat(null);
    setPlayhead(null);
    const url = chatRef.current.url;
    setChat({ url, messages: [] });
    syncVoiceTo([]); // clear a live voice session's context too, not just the visible chat
    if (url) {
      void clearChat(url);
      // The handover walkthrough lives in its OWN per-PR key (drift:handover:<url>), so
      // clearing the conversation must end it too — otherwise a fresh "walk me through the
      // PR" RESUMES at the old cursor (e.g. file 2/60) instead of starting over.
      void clearHandoverSession(url);
    }
    if (ctx) startReasoning(ctx);
  }

  const showDownloadBanner = brainState === 'needs-download' || brainState === 'downloading' || brainState === 'error';

  return (
    <div className="drift-app drift-root">
      <header className="app-bar">
        <span className="drift-logo" />
        <h1>{APP_NAME}</h1>
        <span className="spacer" />
        <button className="iconbtn" title="Rescan this page" onClick={() => void refresh()}>
          ↻
        </button>
        {ctx && (
          <button className="iconbtn ctx-btn" title="Loaded context" onClick={onOpenContext}>
            📎<span className="ctx-btn-count">{ctx.artifacts.length}</span>
          </button>
        )}
        <button className="iconbtn" title="New chat" onClick={newChat} disabled={messages.length === 0}>
          ＋
        </button>
        <button
          className="iconbtn"
          title="Live pipeline — run the scan + render the PR comment here (no AI)"
          onClick={onOpenPipeline}
        >
          ⚡
        </button>
        <button className="iconbtn" title="Settings" onClick={onOpenSettings}>
          ⚙
        </button>
      </header>

      {toolState.pr && (
        <div className="pr-chip">
          <a
            className="pr-chip-link"
            href={toolState.url ?? undefined}
            target="_blank"
            rel="noreferrer"
            title={toolState.title ?? undefined}
          >
            {toolState.pr.repo}#{toolState.pr.number}
          </a>
          <span className={`pr-chip-scan ${toolState.scanRunning ? 'running' : toolState.scanRan ? 'done' : 'none'}`}>
            {toolState.scanRunning
              ? '● scanning…'
              : toolState.scanRan
                ? `✓ scanned${toolState.changedCount != null ? ` · ${toolState.changedCount} file(s)` : ''}`
                : '○ not scanned'}
          </span>
          {toolState.scanRunning && (
            <button className="pr-chip-stop" onClick={stopGenerating} title="Stop the scan">
              ■ Stop
            </button>
          )}
        </div>
      )}

      {showDownloadBanner && (
        <div className="brain-banner">
          {brainState === 'downloading' ? (
            <>
              <span className="spinner" />
              <span className="brain-banner-text">{dlProgress?.phase ?? 'Downloading AI model…'}</span>
              {dlProgress?.fraction != null && (
                <span className="brain-banner-pct">{Math.round(dlProgress.fraction * 100)}%</span>
              )}
            </>
          ) : brainState === 'error' ? (
            <>
              <span className="brain-banner-text">⚠️ {dlProgress?.phase ?? 'Download failed'}</span>
              <button className="brain-banner-btn" onClick={startDownload}>
                Retry
              </button>
            </>
          ) : (
            <>
              <span className="brain-banner-text">Download the on-device AI model to start chatting (~1.1 GB, one time).</span>
              <button className="brain-banner-btn" onClick={startDownload}>
                Download AI model
              </button>
            </>
          )}
        </div>
      )}

      <div className="chat-scroll" ref={scrollRef}>
        {messages.length === 0 ? (
          <div className="chat-empty">
            <div className="mark" />
            <h2>How can I help?</h2>
            <p>Ask about the PR or file you’re viewing. Use “/” for commands.</p>
          </div>
        ) : (
          messages.map((m) =>
            m.tool ? (
              <ToolStep key={m.id} tool={m.tool} />
            ) : m.steps ? (
              <ReasoningTurn
                key={m.id}
                title={m.title}
                steps={m.steps}
                thinking={!!m.thinking}
                files={ctx?.artifacts}
                onOpenFile={setModalFile}
              />
            ) : (
              <div key={m.id} className={`msg ${m.role}`}>
                <div className={`bubble ${m.role === 'assistant' ? 'muted' : ''}`}>
                  {m.presentation && m.presentation.beats.length > 0 ? (
                    // A handover file step renders as a STRUCTURED playbook: intro + inline
                    // sections (button + note, active one lit with the page) + outro + a
                    // hideable replay timeline — not a raw prose blob.
                    <PresentationMessage
                      pres={m.presentation}
                      activeIndex={activeBeat?.msgId === m.id ? activeBeat.index : undefined}
                      pausedIndex={pausedBeat?.msgId === m.id ? pausedBeat.index : undefined}
                      clock={playhead?.msgId === m.id ? playhead : undefined}
                      onPlayFrom={(i) => onBeatClick(m.id, m.presentation!, i)}
                      onResume={resumePresentation}
                      soundEnabled={mode === 'voice' || settings.graphSoundEnabled !== false}
                    />
                  ) : (
                    <>
                      {m.text}
                      {m.thinking && <span className="cursor">▌</span>}
                    </>
                  )}
                </div>
              </div>
            ),
          )
        )}
        {/* Spoken summary, when the PR's comment linked one — playable inline. */}
        {ctx?.audio && messages.length > 0 && <AudioSummary audio={ctx.audio} />}
      </div>

      {mode === 'voice' ? (
        <div className="voice-panel">
          <VoiceOrb mode={voiceState} levelRef={voiceLevel} height={248} />
          <div className="voice-state-label">
            {voiceState === 'listening'
              ? 'Listening…'
              : voiceState === 'thinking'
                ? 'Thinking…'
                : voiceState === 'speaking'
                  ? 'Speaking…'
                  : 'Starting…'}
          </div>
          {voiceStatus && <div className="voice-substatus">{voiceStatus}</div>}
          <button className="voice-exit" onClick={() => void exitVoiceMode()}>
            End voice mode
          </button>
        </div>
      ) : (
      <div className="composer">
        <div className="composer-box">
          {ctx && (
            <div className="attach-row">
              {ctx.artifacts.map((a) => (
                <button
                  key={a.url ?? a.name}
                  className="attach-chip"
                  onClick={() => setModalFile(a)}
                  title={`Open ${a.name}`}
                >
                  <FileIcon size={16} />
                  <span className="attach-name">{a.name}</span>
                </button>
              ))}
            </div>
          )}
          <textarea
            rows={1}
            placeholder={brainState === 'unsupported' ? 'On-device AI needs WebGPU (unavailable here)' : 'Type / for commands'}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={onKeyDown}
          />
          <div className="composer-row">
            <button
              className="ask-toggle"
              data-on={settings.askBeforeActing}
              onClick={() => void patchSettings({ askBeforeActing: !settings.askBeforeActing })}
              title="Toggle whether actions need confirmation"
            >
              {settings.askBeforeActing ? '✋ Ask before acting' : '⚡ Act automatically'}
            </button>
            {voiceStatus && <span className="voice-status">{voiceStatus}</span>}
            <button
              className="mic"
              onClick={() => void enterVoiceMode()}
              disabled={brainState !== 'ready' || busy}
              title="Hands-free voice mode"
            >
              🎙
            </button>
            {busy ? (
              <button className="send stop" onClick={stopGenerating} title="Stop">
                ■
              </button>
            ) : (
              <button className="send" onClick={send} disabled={!draft.trim()} title="Send">
                ↑
              </button>
            )}
          </div>
        </div>
        <div className="composer-foot">{APP_NAME} is AI and can make mistakes.</div>
      </div>
      )}

      {modalFile && <FileModal artifact={modalFile} onClose={() => setModalFile(null)} />}
    </div>
  );
}

/** Human labels for the agent's tools, for the tool-step card. The specialized
 *  agents contribute their own `label` (single source of truth in agents/lenses.ts)
 *  so a card never shows a raw underscored tool id. */
const TOOL_LABELS: Record<string, string> = {
  run_live_pr_scan: 'Running PR scan',
  list_changed_files: 'Listing changed files',
  get_pr_architecture: 'Mapping architecture',
  explain_architecture: 'Reading the code',
  ...Object.fromEntries(LENSES.map((l) => [l.id, l.label])),
};

// The STRUCTURED handover file message — a guided playbook, not a prose blob:
//   • intro header ("Opened X — file N of M")
//   • the SECTION list: one row per spot = an INLINE clickable button (the symbol /
//     line label) + its one-line note. The row whose code the page is CURRENTLY on
//     (`activeIndex`) lights up IN LOCKSTEP with the scroll, so the reviewer sees the
//     exact spot under discussion; a manual-scroll pause marks its row + offers Resume.
//   • outro footer ("Proceed to Y?")
//   • a HIDEABLE timeline scrubber to replay from the start or seek any section.
// Clicking any button/segment plays from that spot.
function PresentationMessage({
  pres,
  activeIndex,
  pausedIndex,
  clock,
  onPlayFrom,
  onResume,
  soundEnabled,
}: {
  pres: FilePresentation;
  activeIndex?: number;
  pausedIndex?: number;
  clock?: MediaClock;
  onPlayFrom: (index: number) => void;
  onResume?: () => void;
  /** Effective default for the diagram's reveal sound (voice → on; text → setting). */
  soundEnabled: boolean;
}) {
  const [showTimeline, setShowTimeline] = useState(true); // visible by default so the playhead is seen
  const [showGraph, setShowGraph] = useState(true); // the change-impact diagram, open by default
  // The Level 1 + Level 2 box IS the first timeline beat (the "Overview" sweep): clicking it
  // starts at the top of the file and slow-scrolls down to the changes while L1+L2 are read.
  const overviewIndex = pres.beats.findIndex((b) => b.sweep);
  const overviewActive = overviewIndex >= 0 && overviewIndex === activeIndex;
  const overviewPaused = overviewIndex >= 0 && overviewIndex === pausedIndex;
  // Drive the change-impact graph from the active beat: while a beat plays, zoom the graph
  // to its symbol's node (or, for the overview / line-range beats, the file node). `nonce`
  // = the beat index so the zoom re-fires each step; null when not playing → the graph
  // runs its own build.
  const graphFocus = activeIndex != null ? { name: pres.beats[activeIndex]?.name ?? null, nonce: activeIndex } : null;
  return (
    <div className="present-msg">
      {pres.intro && <div className="present-intro">{pres.intro}</div>}
      {/* The 3-level file framing: Level 1 (PR's change to this file) + Level 2 (what the
          file does) — ALSO the clickable "Overview" beat (the top-of-file sweep) — then the
          per-change sections below as Level 3. */}
      {pres.overview && (
        <div
          className={`present-overview${overviewIndex >= 0 ? ' present-overview-play' : ''}${overviewActive ? ' active' : ''}${overviewPaused ? ' paused' : ''}`}
          role={overviewIndex >= 0 ? 'button' : undefined}
          tabIndex={overviewIndex >= 0 ? 0 : undefined}
          aria-current={overviewActive ? 'true' : undefined}
          title={overviewIndex >= 0 ? 'Play from the top of the file (reads Level 1 + Level 2)' : undefined}
          onClick={overviewIndex >= 0 ? () => onPlayFrom(overviewIndex) : undefined}
          onKeyDown={overviewIndex >= 0 ? (e) => (e.key === 'Enter' || e.key === ' ') && onPlayFrom(overviewIndex) : undefined}
        >
          <div className="present-level">
            <span className="present-level-tag">Level 1 · PR change</span>
            <span className="present-level-text">{pres.overview.prChange}</span>
          </div>
          <div className="present-level">
            <span className="present-level-tag">Level 2 · What the file does</span>
            <span className="present-level-text">{pres.overview.purpose}</span>
          </div>
        </div>
      )}
      {pres.overview && <div className="present-level-tag present-level3">Level 3 · The changes</div>}
      <ol className="present-sections">
        {pres.beats.map((b, i) => {
          if (b.sweep) return null; // the overview sweep is rendered as the Level 1+2 box above
          const active = i === activeIndex;
          const paused = i === pausedIndex;
          return (
            <li
              key={i}
              className={`present-section${active ? ' active' : ''}${paused ? ' paused' : ''}`}
              aria-current={active ? 'true' : undefined}
            >
              <button
                type="button"
                className={`present-beat${active ? ' active' : ''}${paused ? ' paused' : ''}`}
                onClick={() => onPlayFrom(i)}
                title={`Lines ${b.startLine}–${b.endLine} — play from here`}
              >
                <span className="present-beat-dot" aria-hidden="true" />
                {b.label}
              </button>{' '}
              <span className="present-section-note">{b.note}</span>
            </li>
          );
        })}
      </ol>
      {pausedIndex != null && onResume && (
        <button type="button" className="present-resume" onClick={onResume} title="Resume from where you scrolled">
          ▶ Resume
        </button>
      )}
      {pres.outro && <div className="present-outro">{pres.outro}</div>}
      {/* The file-scoped change-impact graph — an interactive diagram with a scope
          timeline that zooms in to the change, then out to the whole file scope. */}
      {pres.graph && (
        <div className="present-graph-row">
          <button
            type="button"
            className="present-timeline-toggle"
            onClick={() => setShowGraph((v) => !v)}
            aria-expanded={showGraph}
            title="Show/hide the change-impact graph"
          >
            {showGraph ? '▾' : '▸'} Change-impact graph
          </button>
          {showGraph && <ChangeImpactGraph graph={pres.graph} soundEnabled={soundEnabled} filePath={pres.path} focus={graphFocus} />}
        </div>
      )}
      <div className="present-timeline-row">
        <button
          type="button"
          className="present-timeline-toggle"
          onClick={() => setShowTimeline((v) => !v)}
          aria-expanded={showTimeline}
          title="Show/hide the playback timeline"
        >
          {showTimeline ? '▾' : '▸'} Timeline
        </button>
        {showTimeline && <PresentationTimeline beats={pres.beats} activeIndex={activeIndex} clock={clock} onSeek={onPlayFrom} />}
      </div>
    </div>
  );
}

// The playback TIMELINE — one segment per spot (sized by its dwell), with a smoothly
// MOVING playhead + a current/total time readout, so the reviewer sees exactly where
// they are while it auto-plays. ↻ replays from the start; clicking a segment seeks.
function PresentationTimeline({
  beats,
  activeIndex,
  clock,
  onSeek,
}: {
  beats: PresentBeat[];
  activeIndex?: number;
  clock?: MediaClock;
  onSeek: (index: number) => void;
}) {
  // Animate `elapsed` each frame WHILE the clock runs; freeze (single paint) otherwise.
  const [elapsed, setElapsed] = useState(0);
  const rafRef = useRef<number | null>(null);
  useEffect(() => {
    if (!clock) {
      setElapsed(0);
      return;
    }
    const tick = () => {
      setElapsed(clockElapsed(clock, Date.now()));
      if (clock.runningSince != null) rafRef.current = requestAnimationFrame(tick);
    };
    tick(); // paint now; keep looping only while actually playing
    return () => {
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    };
  }, [clock]);

  const totalMs = clock?.totalMs ?? planDurationMs(beats, 'text');
  // Segments are sized by dwell (no lead segment), so position the playhead on the
  // SEGMENT timeline: subtract the lead (totalMs − Σ dwell) so it starts at 0 and the
  // line tracks the active segment rather than drifting by the mode lead.
  const segTotal = beats.reduce((sum, b) => sum + Math.max(900, b.dwellMs), 0);
  const lead = Math.max(0, totalMs - segTotal);
  const pct = segTotal > 0 ? Math.min(100, Math.max(0, ((elapsed - lead) / segTotal) * 100)) : 0;
  return (
    <div className="present-timeline" role="group" aria-label="Playback timeline">
      <button type="button" className="present-timeline-replay" onClick={() => onSeek(0)} title="Replay from the start">
        ↻
      </button>
      <div className="present-timeline-track">
        {beats.map((b, i) => (
          <button
            key={i}
            type="button"
            className={`present-timeline-seg${i === activeIndex ? ' active' : ''}${activeIndex != null && i < activeIndex ? ' done' : ''}`}
            style={{ flexGrow: Math.max(900, b.dwellMs) }}
            onClick={() => onSeek(i)}
            title={`${i + 1}. ${b.label}`}
          />
        ))}
        {clock && <span className="present-timeline-head" style={{ left: `${pct}%` }} aria-hidden="true" />}
      </div>
      <span className="present-timeline-pos">{clock ? `${fmtClock(elapsed)} / ${fmtClock(totalMs)}` : `${beats.length} spots`}</span>
    </div>
  );
}

function ToolStep({ tool }: { tool: NonNullable<ChatMessage['tool']> }) {
  const [copied, setCopied] = useState(false);
  const label = TOOL_LABELS[tool.name] ?? tool.name;
  const icon =
    tool.status === 'running' ? <span className="spinner" /> : tool.status === 'done' ? '✓' : tool.status === 'stopped' ? '■' : '✗';
  // On failure we captured a developer report (error + context + progress log).
  // Offer it as a one-click copy so it can be pasted into a bug report.
  const copyDetails = () => {
    if (!tool.details) return;
    void navigator.clipboard.writeText(tool.details).then(
      () => {
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      },
      () => {},
    );
  };
  return (
    <div className={`tool-step ${tool.status}`}>
      <span className="tool-step-icon">{icon}</span>
      <span className="tool-step-label">{label}</span>
      {tool.status === 'running' && tool.note && <span className="tool-step-note">{tool.note}</span>}
      {tool.status !== 'running' && tool.summary && <span className="tool-step-summary">{tool.summary}</span>}
      {tool.status === 'error' && tool.details && (
        <button className="tool-step-copy" onClick={copyDetails} title="Copy the error and logs for developers">
          {copied ? 'Copied' : 'Copy details'}
        </button>
      )}
    </div>
  );
}

function ReasoningTurn({
  title,
  steps,
  thinking,
  files,
  onOpenFile,
}: {
  title?: string;
  steps: ReasoningStep[];
  thinking: boolean;
  files?: ArtifactRef[];
  onOpenFile?: (a: ArtifactRef) => void;
}) {
  return (
    <div className="reasoning">
      <div className="reasoning-head">
        {thinking ? <span className="spinner" /> : <span className="reasoning-check">✓</span>}
        <span>{thinking ? title ?? 'Thinking…' : title ?? 'Reasoned'}</span>
      </div>
      <ol className="reasoning-steps">
        {steps.map((s, i) => (
          <li key={i} className={`rs-${s.level}`}>
            {s.text}
          </li>
        ))}
        {thinking && (
          <li className="rs-typing">
            <span className="dot" />
            <span className="dot" />
            <span className="dot" />
          </li>
        )}
      </ol>
      {!thinking && files && files.length > 0 && (
        <div className="reasoning-files">
          <span className="rfiles-label">Download:</span>
          {files.map((f) => (
            <button key={f.url ?? f.name} className="rfile-btn" onClick={() => onOpenFile?.(f)}>
              <FileIcon size={14} />
              <span>{f.name}</span>
              <span className="rfile-dl">⬇</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
