use crate::ImportRecord;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

/// Resource category for a static call.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Category {
    Db,
    Network,
    Io,
    Cache,
    Queue,
    Log,
    Compute,
}

impl Category {
    pub const ALL: &'static [Category] = &[
        Category::Db,
        Category::Network,
        Category::Io,
        Category::Cache,
        Category::Queue,
        Category::Log,
        Category::Compute,
    ];

    pub fn as_str(&self) -> &'static str {
        match self {
            Category::Db => "db",
            Category::Network => "network",
            Category::Io => "io",
            Category::Cache => "cache",
            Category::Queue => "queue",
            Category::Log => "log",
            Category::Compute => "compute",
        }
    }
}

/// Result of classifying a single call site, with the evidence used.
/// Useful for the UI ("we said DB because the receiver `session` was bound to
/// `sqlalchemy.orm.Session`").
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Classification {
    pub category: Category,
    pub tier: ClassifyTier,
    pub evidence: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClassifyTier {
    /// Tier B: receiver is a directly-imported module from a catalogued lib
    ImportedModule,
    /// Tier C: receiver name matches a well-known pattern (e.g. `session`, `axios`)
    ReceiverPattern,
    /// Tier D: method name is unambiguous in any context
    MethodSignature,
}

/// Classify a call site given its method name, optional receiver, and the file's imports.
///
/// Strategy (tier order):
///   B. If receiver is a name imported from a catalogued module → use that category
///   C. If receiver name matches a well-known receiver pattern → that category
///   D. If method name is unambiguous on its own → that category
///   Else → None (likely user code)
///
/// The "ambiguous-on-its-own" method names (`save`, `add`, `find`, `update`, ...)
/// are deliberately excluded from Tier D. They require Tier B or C evidence.
pub fn classify(
    name: &str,
    receiver: Option<&str>,
    imports: &[ImportRecord],
) -> Option<Classification> {
    // Tier B: receiver bound to an imported categorized module.
    //
    // Two match shapes:
    //   1. Direct: receiver equals the import's local binding. Python's
    //      `import sqlalchemy` + `sqlalchemy.func()` lands here.
    //   2. Crate-root / package-root: receiver equals the first segment of
    //      the module path. Rust's `use sqlx::PgPool` does NOT shadow the
    //      crate root, so `sqlx::query_as()` still resolves to the sqlx
    //      crate even though the local binding is `PgPool`. Same shape in
    //      Java: `import com.foo.Bar; com.foo.…()`. We always check the
    //      first segment regardless of separator (`.`, `::`, `/`).
    if let Some(r) = receiver {
        for imp in imports {
            let direct = imp.local_name == r;
            let root_segment = imp
                .module_path
                .split(|c: char| c == '.' || c == '/' || c == ':')
                .find(|s| !s.is_empty());
            let root_match = root_segment == Some(r);
            if direct || root_match {
                if let Some(cat) = classify_module(&imp.module_path) {
                    return Some(Classification {
                        category: cat,
                        tier: ClassifyTier::ImportedModule,
                        evidence: format!("receiver `{}` imported from `{}`", r, imp.module_path),
                    });
                }
            }
        }
    }

    // Tier C: receiver name pattern
    if let Some(r) = receiver {
        if let Some(cat) = classify_receiver_pattern(r) {
            return Some(Classification {
                category: cat,
                tier: ClassifyTier::ReceiverPattern,
                evidence: format!("receiver name `{r}` matches {} pattern", cat.as_str()),
            });
        }
    }

    // Tier D: unambiguous method name
    if let Some(cat) = classify_unambiguous_method(name) {
        return Some(Classification {
            category: cat,
            tier: ClassifyTier::MethodSignature,
            evidence: format!("method `{name}` is an unambiguous {} call", cat.as_str()),
        });
    }

    None
}

// ───────────────────────────────────────────────────────────────────────────
// Data-driven catalog loading
// ───────────────────────────────────────────────────────────────────────────
//
// We embed JSON catalogs at compile time via `include_str!`. Source-of-truth
// for the per-language files is `research_classefiers+categories/`, which is
// generated by `generate.py` from the OpenTelemetry registry + hand-curated
// seeds. The `module_overrides.json` file supplements those with entries we
// rely on but the upstream catalogs don't yet cover (e.g. `django.db`).
//
// Tier C / Tier D heuristics live in dedicated JSON files in the same dir.

#[derive(Deserialize)]
struct ModuleCatalogFile {
    entries: Vec<ModuleCatalogEntry>,
}

#[derive(Deserialize)]
struct ModuleCatalogEntry {
    module: String,
    category: Category,
}

#[derive(Deserialize)]
struct ReceiverPatternsFile {
    patterns: Vec<NamedCategory>,
}

#[derive(Deserialize)]
struct UnambiguousMethodsFile {
    methods: Vec<NamedCategory>,
}

#[derive(Deserialize)]
struct NamedCategory {
    name: String,
    category: Category,
}

// Per-language module catalogs are the canonical source-of-truth, extended
// in place by `build_otel_registry.py` (which merges entries derived from
// the OpenTelemetry registry YAMLs in `categories-opentelemetry-classefiers/`,
// deduping by module name — existing entries win on conflict). `module_overrides.json`
// supplements with hand-curated cross-language additions.
const MODULE_CATALOG_FILES: &[&str] = &[
    include_str!("research_classefiers+categories/python.json"),
    include_str!("research_classefiers+categories/javascript.json"),
    include_str!("research_classefiers+categories/java.json"),
    include_str!("research_classefiers+categories/go.json"),
    include_str!("research_classefiers+categories/rust.json"),
    include_str!("research_classefiers+categories/scala.json"),
    include_str!("research_classefiers+categories/module_overrides.json"),
];

// Tier C and Tier D each live in a single file, extended in place by the
// same merge script (Tier C from OTel library names, Tier D from the
// curated dict inside `build_otel_registry.py`).
const RECEIVER_PATTERNS_FILE: &str =
    include_str!("research_classefiers+categories/receiver_patterns.json");

const UNAMBIGUOUS_METHODS_FILE: &str =
    include_str!("research_classefiers+categories/unambiguous_methods.json");

static MODULE_CATALOG: OnceLock<Vec<(String, Category)>> = OnceLock::new();
static RECEIVER_PATTERNS: OnceLock<Vec<(String, Category)>> = OnceLock::new();
static UNAMBIGUOUS_METHODS: OnceLock<Vec<(String, Category)>> = OnceLock::new();

fn module_catalog() -> &'static [(String, Category)] {
    MODULE_CATALOG.get_or_init(|| {
        let mut out: Vec<(String, Category)> = Vec::new();
        for raw in MODULE_CATALOG_FILES {
            let f: ModuleCatalogFile =
                serde_json::from_str(raw).expect("module catalog json should parse");
            for e in f.entries {
                out.push((e.module, e.category));
            }
        }
        // Longest prefix wins: ensures `org.springframework.data` is checked
        // before `org.springframework`, and `django.db` before `django`.
        out.sort_by(|a, b| b.0.len().cmp(&a.0.len()));
        out
    })
}

fn receiver_patterns() -> &'static [(String, Category)] {
    RECEIVER_PATTERNS.get_or_init(|| {
        let f: ReceiverPatternsFile = serde_json::from_str(RECEIVER_PATTERNS_FILE)
            .expect("receiver patterns json should parse");
        f.patterns
            .into_iter()
            .map(|p| (p.name, p.category))
            .collect()
    })
}

fn unambiguous_methods() -> &'static [(String, Category)] {
    UNAMBIGUOUS_METHODS.get_or_init(|| {
        let f: UnambiguousMethodsFile = serde_json::from_str(UNAMBIGUOUS_METHODS_FILE)
            .expect("unambiguous methods json should parse");
        f.methods
            .into_iter()
            .map(|m| (m.name, m.category))
            .collect()
    })
}

/// CATALOG — module path → category, prefix-based.
///
/// `sqlalchemy.orm` matches `sqlalchemy`; `org.springframework.data.jpa`
/// matches `org.springframework.data`. We accept `.`, `/`, and `::` as
/// segment separators to cover Python/Java, Go module paths, and Rust crate
/// paths uniformly.
///
/// Catalog data comes from `research_classefiers+categories/*.json` —
/// six per-language files synthesized from the OpenTelemetry registry +
/// hand-curated seeds, plus `module_overrides.json` for gap-filling.
pub fn classify_module(module: &str) -> Option<Category> {
    for (prefix, cat) in module_catalog() {
        if module == prefix
            || module.starts_with(&format!("{prefix}."))
            || module.starts_with(&format!("{prefix}/"))
            // Rust uses `::` between crate root and child paths
            // (`sqlx::PgPool`).
            || module.starts_with(&format!("{prefix}::"))
        {
            return Some(*cat);
        }
    }
    None
}

/// Receiver-name patterns — strong hints even when type info is missing.
/// Example: `session.add(...)` → DB regardless of where `session` came from.
///
/// Patterns are loaded from `research_classefiers+categories/receiver_patterns.json`.
/// Matched against the lowercased receiver name exactly (no prefix).
pub fn classify_receiver_pattern(receiver: &str) -> Option<Category> {
    let lower = receiver.to_ascii_lowercase();
    receiver_patterns()
        .iter()
        .find(|(n, _)| *n == lower)
        .map(|(_, c)| *c)
}

/// Unambiguous method names — these almost always indicate the category in any
/// language/framework. Deliberately tight; generic verbs like `save`, `add`,
/// `find`, `get`, `delete`, `update` are NOT here.
///
/// Loaded from `research_classefiers+categories/unambiguous_methods.json`.
/// Matched case-sensitively against the method name exactly.
pub fn classify_unambiguous_method(name: &str) -> Option<Category> {
    unambiguous_methods()
        .iter()
        .find(|(n, _)| n == name)
        .map(|(_, c)| *c)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn imp(local: &str, module: &str) -> ImportRecord {
        ImportRecord {
            local_name: local.into(),
            module_path: module.into(),
            imported_name: None,
            line: 0,
        }
    }

    #[test]
    fn imported_module_wins_tier_b() {
        let imports = vec![imp("requests", "requests")];
        let c = classify("get", Some("requests"), &imports).unwrap();
        assert_eq!(c.category, Category::Network);
        assert_eq!(c.tier, ClassifyTier::ImportedModule);
    }

    #[test]
    fn receiver_pattern_catches_session_add() {
        // No imports, just the receiver name
        let c = classify("add", Some("session"), &[]).unwrap();
        assert_eq!(c.category, Category::Db);
        assert_eq!(c.tier, ClassifyTier::ReceiverPattern);
    }

    #[test]
    fn unambiguous_method_classifies_jdbc() {
        let c = classify("executeQuery", None, &[]).unwrap();
        assert_eq!(c.category, Category::Db);
        assert_eq!(c.tier, ClassifyTier::MethodSignature);
    }

    #[test]
    fn no_false_positive_on_set_add() {
        // `seen.add(item)` — receiver "seen", method "add", no imports
        assert!(classify("add", Some("seen"), &[]).is_none());
    }

    #[test]
    fn no_false_positive_on_dict_update() {
        assert!(classify("update", Some("result"), &[]).is_none());
    }

    #[test]
    fn no_false_positive_on_list_find() {
        assert!(classify("find", Some("items"), &[]).is_none());
    }

    #[test]
    fn no_false_positive_on_save_to_disk() {
        // "save" alone, no receiver context, no imports → not categorized
        assert!(classify("save", None, &[]).is_none());
    }

    #[test]
    fn axios_get_classifies_network() {
        let imports = vec![imp("axios", "axios")];
        let c = classify("get", Some("axios"), &imports).unwrap();
        assert_eq!(c.category, Category::Network);
    }

    #[test]
    fn prisma_user_create_classifies_db() {
        // `prisma.user.create({...})` → receiver text is `user`, but we
        // catch it via the receiver-pattern bucket (`model`) — and if we
        // can see the import `prisma`, the receiver-pattern fallback isn't
        // even needed. Verify the pattern path:
        // The query gives us receiver="user" for `prisma.user.create(...)`.
        // `user` isn't a receiver pattern, but `prisma` IS. So if the
        // analyzer captures the chain we'd want `prisma`. Confirm both paths.
        // Path 1: receiver = "prisma" (direct call on the imported binding)
        let imports = vec![imp("prisma", "@prisma/client")];
        let c = classify("create", Some("prisma"), &imports).unwrap();
        assert_eq!(c.category, Category::Db);
        // Path 2: receiver = "user" — no Tier B match; receiver pattern doesn't include "user"
        assert!(classify("create", Some("user"), &imports).is_none());
    }

    // ─── New tests for data-driven loading ──────────────────────────────

    #[test]
    fn catalog_loads_and_is_sorted_longest_first() {
        let cat = module_catalog();
        assert!(!cat.is_empty(), "module catalog must load");
        for w in cat.windows(2) {
            assert!(
                w[0].0.len() >= w[1].0.len(),
                "catalog must be sorted longest-prefix-first; got {} before {}",
                w[0].0,
                w[1].0,
            );
        }
    }

    #[test]
    fn django_db_beats_django_in_prefix_match() {
        // Regression: `django.db.models` must classify as Db (from
        // `django.db`), not Network (from `django`). Verifies the
        // longest-prefix-wins sort survives the data-driven refactor.
        assert_eq!(classify_module("django.db.models"), Some(Category::Db));
        assert_eq!(classify_module("django.urls"), Some(Category::Network));
    }

    #[test]
    fn spring_data_beats_spring_web_for_jpa_path() {
        // `org.springframework.data.jpa.repository` → Db
        assert_eq!(
            classify_module("org.springframework.data.jpa.repository"),
            Some(Category::Db),
        );
    }

    #[test]
    fn rust_double_colon_prefix_matches() {
        // `use sqlx::PgPool` → module_path "sqlx::PgPool"
        assert_eq!(classify_module("sqlx::PgPool"), Some(Category::Db));
        assert_eq!(classify_module("tokio::fs::File"), Some(Category::Io));
    }

    #[test]
    fn go_slash_prefix_matches() {
        assert_eq!(
            classify_module("github.com/jackc/pgx/v5"),
            Some(Category::Db),
        );
        assert_eq!(classify_module("net/http"), Some(Category::Network));
    }

    #[test]
    fn receiver_patterns_load_and_match_lowercase() {
        // Mixed-case receiver should still match (we lowercase before lookup)
        assert_eq!(classify_receiver_pattern("Session"), Some(Category::Db));
        assert_eq!(classify_receiver_pattern("HTTPClient"), Some(Category::Network));
        assert_eq!(classify_receiver_pattern("Logger"), Some(Category::Log));
    }

    #[test]
    fn unknown_module_returns_none() {
        assert!(classify_module("my.custom.user.code").is_none());
    }

    // ─── Tests for OTel-derived (build_otel_registry.py) data ──────────

    #[test]
    fn otel_registry_module_is_loaded_tier_b() {
        // `jedis` is a Java Redis client. Only present in otel_registry.json,
        // not in the hand-maintained per-language catalogs. If this passes
        // the OTel-derived module data is reaching the classifier.
        assert_eq!(classify_module("jedis"), Some(Category::Cache));
    }

    #[test]
    fn otel_derived_receiver_pattern_is_loaded_tier_c() {
        // `jedis` is auto-promoted to a Tier C receiver pattern from the
        // OTel registry. The hand-curated receiver_patterns.json does not
        // include it.
        assert_eq!(classify_receiver_pattern("jedis"), Some(Category::Cache));
    }

    #[test]
    fn otel_curated_method_is_loaded_tier_d() {
        // `hgetall` is a Redis-specific method curated in
        // build_otel_registry.py → otel_unambiguous_methods.json.
        assert_eq!(classify_unambiguous_method("hgetall"), Some(Category::Cache));
        // `insertOne` is Mongo-specific.
        assert_eq!(classify_unambiguous_method("insertOne"), Some(Category::Db));
        // `basicPublish` is AMQP / RabbitMQ.
        assert_eq!(classify_unambiguous_method("basicPublish"), Some(Category::Queue));
    }
}
